# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Build docker image

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
    TZ: Asia/Shanghai
    IMAGE_NAME: cors-anywhere

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Set up Docker BuildX
      uses: docker/setup-buildx-action@v2

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.PACKAGE_TOKEN }}

    - name: Build && Push
      uses: docker/build-push-action@v3
      with:
          context: ./
          push: true
          platforms: linux/amd64,linux/arm64
          file: ./Dockerfile
          tags: ghcr.io/${{ github.actor | lower }}/${{ env.IMAGE_NAME }}:latest

        # Delete all pre-release package versions except latest 5
    - uses: actions/delete-package-versions@v3
      with:
          package-name: ${{ env.IMAGE_NAME }}
          min-versions-to-keep: 5
#        delete-only-pre-release-versions: "true"
